import type { Document } from '@/types/api'

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: '1',
    user_id: 'user-1',
    filename: 'Q4-2025-Financial-Report.pdf',
    file_size: 2_450_000,
    status: 'completed',
    total_chunks: 45,
    processed_chunks: 45,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    processed_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    user_id: 'user-1',
    filename: 'Product-Roadmap-2026.docx',
    file_size: 890_000,
    status: 'completed',
    total_chunks: 22,
    processed_chunks: 22,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    processed_at: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    user_id: 'user-1',
    filename: 'Sales-Data-Q3-2025.xlsx',
    file_size: 1_200_000,
    status: 'processing',
    total_chunks: 30,
    processed_chunks: 18,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    processed_at: null,
  },
  {
    id: '4',
    user_id: 'user-1',
    filename: 'Team-Presentation-Onboarding.pptx',
    file_size: 5_600_000,
    status: 'completed',
    total_chunks: 60,
    processed_chunks: 60,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    processed_at: new Date(Date.now() - 1.9 * 86400000).toISOString(),
  },
  {
    id: '5',
    user_id: 'user-1',
    filename: 'Meeting-Notes-2025-12-10.txt',
    file_size: 15_000,
    status: 'completed',
    total_chunks: 3,
    processed_chunks: 3,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    processed_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: '6',
    user_id: 'user-1',
    filename: 'API-Documentation.md',
    file_size: 45_000,
    status: 'failed',
    total_chunks: 8,
    processed_chunks: 2,
    error_message: 'Unsupported encoding detected',
    metadata: null,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    processed_at: null,
  },
  {
    id: '7',
    user_id: 'user-1',
    filename: 'Budget-Proposal-2026.pdf',
    file_size: 3_100_000,
    status: 'pending',
    total_chunks: 0,
    processed_chunks: 0,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    processed_at: null,
  },
  {
    id: '8',
    user_id: 'user-1',
    filename: 'Employee-Handbook-v3.pdf',
    file_size: 8_500_000,
    status: 'completed',
    total_chunks: 120,
    processed_chunks: 120,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    processed_at: new Date(Date.now() - 9.8 * 86400000).toISOString(),
  },
  {
    id: '9',
    user_id: 'user-1',
    filename: 'Marketing-Campaign-Analysis.xlsx',
    file_size: 950_000,
    status: 'completed',
    total_chunks: 18,
    processed_chunks: 18,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    processed_at: new Date(Date.now() - 6.9 * 86400000).toISOString(),
  },
  {
    id: '10',
    user_id: 'user-1',
    filename: 'Architecture-Decision-Records.md',
    file_size: 28_000,
    status: 'completed',
    total_chunks: 5,
    processed_chunks: 5,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    processed_at: new Date(Date.now() - 13.9 * 86400000).toISOString(),
  },
  {
    id: '11',
    user_id: 'user-1',
    filename: 'Quarterly-OKRs-Q1-2026.pdf',
    file_size: 1_800_000,
    status: 'processing',
    total_chunks: 25,
    processed_chunks: 10,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    processed_at: null,
  },
  {
    id: '12',
    user_id: 'user-1',
    filename: 'Customer-Feedback-Survey-Results.pptx',
    file_size: 4_200_000,
    status: 'completed',
    total_chunks: 48,
    processed_chunks: 48,
    error_message: null,
    metadata: null,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    processed_at: new Date(Date.now() - 3.8 * 86400000).toISOString(),
  },
]
